
# Site settings
title: Is Overfitting Necessary for Implicit Video Representation?

author:
  name: saitmerong
  email: saitmerong@gmail.com  
description: "Visualization Results"

# Build settings
# remote_theme: jekyll/minima


# theme: jekyll-theme-slate
theme: jekyll-theme-cayman
github:
  is_project_page: false